### ISSUE TITLE
implement chatroom and messaging functionality

### ISSUE THREAD

**Issue by M-max-cell** [kianhk6/SFULounge#3]

**Comment by M-max-cell** [comment]
@Divij11 
folder: /ui/chats
implement messages:
- MessagingActivity
- get messages for chat room: db.collection("messages").document(chatRoomId).get()
- register for message updates
- sending message: db.collection("messages")..document(chatRoomId).add(...).continueWithTask(... get the message id here ... ref.update("messageId", task.result.id)
- implement paging with paging 3 library
- scroll up to lazy load older messages
- handle uploading text, files, images (and audio if you have time)
- wiring with the ChatsFragment onItemClick

**Comment by kianhk6** [comment]
for safety reasons I really wouldnt mind leaving out images
