### ISSUE TITLE
Getting an error when finishing register in the setUpImagesActivity 

### ISSUE THREAD

**Issue by kianhk6** [kianhk6/SFULounge#34]
java.lang.RuntimeException: Unable to destroy activity {com.example.sfulounge/com.example.sfulounge.ui.setup.SetupImagesActivity}: java.util.ConcurrentModificationException

**Comment by kianhk6** [comment]
@M-max-cell bug still exists

**Comment by M-max-cell** [comment]
I'm not able to replicate this error @kianhk6. Can you provide more details?
